# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b721f54a0c3ef86f45b321f4b4ecf121a7b5f68c7da0a4dbd1d741ec010c14ded82d09ffa4a00d6cdecde5949255dc5e271cbd7459ef1639343e7f65150b77f

test:
  secret_key_base: 0deded3a2714cb1865147fbc652e39eb464695f793fffa840aaa5e532d8d90034b3ced67352b02a0f87a18fc8dc3e32a43d910e50514ad2e4ae4e2471de08cd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
